# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box_check_update = false
  config.vm.define "host"
  config.vm.hostname = "hours"
  
  # Forward the default HTTP port of the built in rails development server.
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
     vb.memory = "2048"
  end
  
  config.vm.provision :shell, path: "ruby.sh", privileged: false
  config.vm.provision :shell, path: "app.sh", privileged: false
  
 
end
