
version: "2"

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: hours
      POSTGRES_PASSWORD: hours
    ports:
      - "5432:5432"
    volumes:
      - backupvol:/var/lib/postgresql/data

  cache:
    image: memcached:1.4
    volumes:
      - cachevol:/var/lib/redis/data

  app:
    build: . #path to the Dockerfile
    env_file: .env
    depends_on:
      - db
      - cache
    volumes:
      - .:/hours
    ports: 
      - "8080:7000"

volumes:
  backupvol:
  cachevol:


    

    
