
version: "2"

services:
  db:
    image: postgres:9.4
#    environment:
#      POSTGRES_USER: hours
#      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    ports:
      - "6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    build: ./app/ 
    env_file: ./app/.env
    depends_on:
      - db
      - redis
    ports: 
      - "7000:7000"
    volumes:
      - ./app/:/hours


  proxy:
    build: ./proxy/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx


volumes:
  data:
  redis:

