
version: "2"

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: hours
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  web:
    build: ./web/ 
    env_file: ./web/.env
    depends_on:
      - db
      - redis
    ports: 
      - "7000"
    volumes:
      - ./web/:/hours


  proxy:
    build: ./proxy/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx


volumes:
  data:
  redis:


    

    
