development: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: hours_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  port: 5432

test:
  <<: *default
  database: hours_test

production:
  <<: *default
  database: hours_production